# Generated by Django 2.2 on 2019-06-24 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20190505_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='about',
            new_name='description',
        ),
    ]
